@startuml
' This plugin integrates all type diagram snippets. They are splitted into 9 sections:

class Enkoder{
    Angle:  12bit
}

class STM32{
    
}

' class Motor_driver{
'     Enable: 1
'     Clk: Step
'     Cw: direction
' }

' class Motor{

' }

' ' class MATLAB_APP{

' ' }

' class MATLAB_SCRIPT{
'     Velocity: To_Send2Motor
'     Logs: To_SDCard
' }


Enkoder --> STM32
' STM32 --> MATLAB_SCRIPT
' ' MATLAB_APP "zadana wartosc"--> MATLAB_SCRIPT
' MATLAB_SCRIPT "syg sterujacy - predkosc" --> STM32
' STM32 "Freq, VIN, GND" --> Motor_driver
' Motor_driver --> Motor
' Motor --> Enkoder
STM32 "USART" --> Terminal
@enduml